### ISSUE TITLE
Node.js  Loaders Team Meeting 2023-09-12

### ISSUE THREAD

**Issue by mhdawson** [nodejs/loaders#160] opened 2023-09-08 12:05 UTC
## Time

**UTC Tue 12-Sep-2023 18:00 (06:00 PM)**:

| Timezone      | Date/Time             |
|---------------|-----------------------|
| US / Pacific  | Tue 12-Sep-2023 11:00 (11:00 AM) |
| US / Mountain | Tue 12-Sep-2023 12:00 (12:00 PM) |
| US / Central  | Tue 12-Sep-2023 13:00 (01:00 PM) |
| US / Eastern  | Tue 12-Sep-2023 14:00 (02:00 PM) |
| EU / Western  | Tue 12-Sep-2023 19:00 (07:00 PM) |
| EU / Central  | Tue 12-Sep-2023 20:00 (08:00 PM) |
| EU / Eastern  | Tue 12-Sep-2023 21:00 (09:00 PM) |
| Moscow        | Tue 12-Sep-2023 21:00 (09:00 PM) |
| Chennai       | Tue 12-Sep-2023 23:30 (11:30 PM) |
| Hangzhou      | Wed 13-Sep-2023 02:00 (02:00 AM) |
| Tokyo         | Wed 13-Sep-2023 03:00 (03:00 AM) |
| Sydney        | Wed 13-Sep-2023 04:00 (04:00 AM) |

Or in your local time:
* https://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Foundation+Loaders%20Team+Meeting+2023-09-12&iso=20230912T1800
* or https://www.wolframalpha.com/input/?i=06PM+UTC%2C+Sep+12%2C+2023+in+local+time

## Links

* Minutes Google Doc: <https://docs.google.com/document/d/1LZcnAFkRvnPNlFjFEK3zqoQe6NHUgcGVeO5UL1RSZu4/edit>

## Agenda

Extracted from **loaders-agenda** labelled issues and pull requests from the **nodejs org** prior to the meeting.

### nodejs/node

* https://github.com/nodejs/node/issues/49432
* esm: remove `globalPreload` hook (superseded by `initialize`) [#49144](https://github.com/nodejs/node/pull/49144)

## Invited

* Loaders team: @nodejs/loaders

## Notes

The agenda comes from issues labelled with `loaders-agenda` across **all of the repositories in the nodejs org**. Please label any additional issues that should be on the agenda before the meeting starts.

## Joining the meeting

* link for participants: <https://zoom.us/j/97506450082>

* For those who just want to watch: <https://www.youtube.com/c/nodejs+foundation/live>

**Comment by GeoffreyBooth** [comment] 2023-09-08 14:26
Adding https://github.com/nodejs/node/issues/49432 to the agenda. @LiviaMedeiros, could you join us in this meeting?

**Comment by LiviaMedeiros** [comment] 2023-09-09 05:09
No; I'll probably watch it next morning. Unless there are any specific questions for the agenda, most of my objections are already outlined in prior discussions anyway.

**Comment by GeoffreyBooth** [comment] 2023-09-09 15:04
> No; I'll probably watch it next morning. Unless there are any specific questions for the agenda, most of my objections are already outlined in prior discussions anyway.

I'm hoping that we can reach a consensus on what to do regarding that proposal. I'd appreciate your input in that discussion. If we decide something and you don't like our conclusion, what then?

Is there a better time that would work for you?

**Comment by JakobJingleheimer** [comment] 2023-09-12 16:53
Are we meeting today?

**Comment by LiviaMedeiros** [comment] 2023-09-12 16:59
> Is there a better time that would work for you?

Sorry for very late response and/or inconvenience; I can't attend. Please proceed without me at the time that is convenient for others.

**Comment by GeoffreyBooth** [comment] 2023-09-12 17:41
I have a sudden conflict, moving the meeting 30 min later. Anyone planning to join besides me and @JakobJingleheimer ?

**Comment by GeoffreyBooth** [comment] 2023-09-12 19:16
@JakobJingleheimer and I chatted. I didn’t record it because it was just us and I don’t think there’s much point in making a “team” decision as two people. But basically we both like the proposal in https://github.com/nodejs/node/issues/49432, and want to try to get it implemented and landed before 21.0.0. We think it shouldn’t be split up into many small flags. @LiviaMedeiros is this something you want to collaborate on?

**Closed** 2023-09-12 20:12 UTC

**Comment by LiviaMedeiros** [comment] 2023-09-13 12:34
I'm not quite sure yet and can't promise anything.

First of all, my opinion that https://github.com/nodejs/node/pull/49531 should go separately still stays, until there is convincing reason to not (I think, correct code behaviour outweights any subjective preferences, even if preferences are understandable and reasonable) or TSC resolution.

As for https://github.com/nodejs/node/issues/49432
- My objection about URL part is completely lifted if the part is removed from proposal.
If it's changed into rework of how `--import` works, I'd like to see if there is consensus on how it should work, consensus on implied breaking changes, and consensus on if the changes would work with that proposal (for example, the latest messages propose to make `--interactive` behave differently depending on the esm flag, which is questionable).
- My objection about limitation to `--import` is lifted because it's no longer a limitation.

Because the solution for making it non-breaking for ecosystem seems to be "it won't work inside of `node_modules`", I'm concerned about performance implications. This kind of check is very expensive. We can accept it as trade-off when it's an experimental flag, but if the plan is to make it eventually work by default, I'm afraid that we will end up with significant regression that we can't work around without breaking ecosystem.

Thus said, I think the main idea of https://github.com/nodejs/node/issues/49432 is feasible but it has too much vagueness right now. Not really a fan of knowingly implementing UB and only then thinking how to fix it; I'd prefer if we had clear detailed image of what we need to achieve and only then start implementing it.
